/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 gradient_block.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GradientBlock(props) {
  const { nodes, materials } = useGLTF('/gltf/web_block/gradient_block.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh  material-color={`#ff0066`}  geometry={nodes.Plano.geometry} material={materials['Materiais.003']} rotation={[1.5, -.1, 0.3]} scale={[1.5, 3, 2]} />
      <mesh geometry={nodes.Plano003.geometry} material={materials['Materiais.004']}  position={[-0.3, -0.2, 1]} rotation={[1.5, -.1, 0.3]} scale={[1.2, 0.1, 1.5]} />
    </group>
  )
}

useGLTF.preload('/gltf/web_block/gradient_block.gltf')


